### ISSUE TITLE
ios13下崩溃闪退   安卓不能选择视频

### ISSUE THREAD

**Issue by simanlx** [Wayaer/picture_picker#1]
`*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff23c7127e __exceptionPreprocess + 350
	1   libobjc.A.dylib                     0x00007fff513fbb20 objc_exception_throw + 48
	2   Foundation                          0x00007fff256c8b22 +[NSBundle bundleWithURL:] + 0
	3   Foundation                          0x00007fff256c8b4f +[NSBundle bundleWithURL:] + 45
	4   Runner                              0x000000010fce838f +[NSBundle(TZImagePicker) tz_imagePickerBundle] + 159
	5   Runner                              0x000000010fd0d381 -[TZImagePickerConfig setPreferredLanguage:] + 513
	6   Runner                              0x000000010fd0d14f __37+[TZImagePickerConfig sharedInstance]_block_invoke + 111
	7   libdispatch.dylib                   0x00007fff5223f7b9 _dispatch_client_callout + 8
	8   libdispatch.dylib                   0x00007fff522409e5 <…>
`

**Comment by Wayaer** [comment]
ios 闪退修复，Android选择视频好像没啥问题啊
